site_name: Autolab Documentation
site_url: "https://docs.autolabproject.com/"
extra_css:
    - stylesheets/extra.css
nav:
    - Autolab:
        - Getting Started: index.md
        - Guide for Instructors: instructors.md
        - Guide for Lab Authors: lab.md
        - Features:
            - Formatted Feedback: features/formatted-feedback.md
            - Scoreboards: features/scoreboards.md
            - Embedded Forms: features/embedded-forms.md
            - Annotations: features/annotations.md
            - MOSS Plagiarism Detection: features/moss.md
            - Metrics: features/metrics.md
    - Installation:
        - Overview: installation/overview.md
        - Docker Compose Install: docker-compose.md
        # - Manual Install: install.md
        - (Legacy) OneClick Install: one-click.md

    - Autolab API:
        - Overview: api-overview.md
        - Reference: api-interface.md
        - Command Line Interface: command-line-interface.md
        - Managing Authorized Apps: api-managing-authorized-apps.md
    - Tango:
        - Getting Started: tango.md
        - Tango CLI: tango-cli.md
        - REST API: tango-rest.md
        - VMMS Docs: tango-vmms.md
        - Deploying Tango: tango-deploy.md
theme:
    name: material
    logo: "images/logo.svg"
    palette:
        scheme: autolab
    features:
        - navigation.tabs
        - toc.integrate
repo_name: "Autolab"
repo_url: "https://github.com/Autolab/autolab"
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/Autolab
        - icon: fontawesome/brands/facebook
          link: "https://facebook.com/autolabproject"
google_analytics:
    - "UA-79424729-3"
    - "auto"
markdown_extensions:
    - admonition
    - codehilite
      #linenums: true
strict: true
plugins:
  - search
