site_name: Autolab Documentation
site_url: "https://docs.autolabproject.com/"
extra_css:
    - stylesheets/extra.css
nav:
    - Overview: index.md
    - Installation:
        - Installation Overview: installation/overview.md
        - Docker Compose Install: installation/docker-compose.md
        - Autolab:
            - Ubuntu 18.04: installation/ubuntu.md
            - Mac OSX 10.11+: installation/osx.md
            - Troubleshooting: installation/troubleshoot.md
            - Mailing Setup: installation/mailing.md
            - Github Integration Setup: installation/github_integration.md
            - LTI Advantage Integration Setup: installation/lti_integration.md
        - Tango: 
            - Installation: installation/tango.md
            - Troubleshooting: installation/tango-troubleshoot.md
        # - (Legacy) OneClick Install: installation/one-click.md
    - Getting Started:
        - Autolab Frontend:
            - Guide for Instructors: instructors.md
            - Guide for Lab Authors: lab.md
            - Features:
                - Formatted Feedback: features/formatted-feedback.md
                - Scoreboards: features/scoreboards.md
                - Embedded Forms: features/embedded-forms.md
                - Schedulers: features/schedulers.md
                - Annotations: features/annotations.md
                - MOSS Plagiarism Detection: features/moss.md
                - Metrics: features/metrics.md
                - Git Submission: features/git-submission.md
                - LTI Course Linking: features/lti-course-integration.md
                - Admin Features: features/admin-features.md
        - Autolab Frontend CLI: command-line-interface.md
        - Tango CLI: tango-cli.md
    - Reference: 
        - Reference Overview: reference.md
        - Autolab Frontend API:
            - Overview: api-overview.md
            - Endpoints: api-interface.md
            - Managing Authorized Apps: api-managing-authorized-apps.md
        - Tango API: tango-rest.md
        - Tango VMMS API: tango-vmms.md
theme:
    name: material
    logo: "images/logo.svg"
    palette:
        scheme: autolab
    features:
        - navigation.tabs
        - toc.integrate
repo_name: "Autolab"
repo_url: "https://github.com/Autolab/autolab"
extra:
    social:
        - icon: fontawesome/brands/github-alt
          link: https://github.com/Autolab
        - icon: fontawesome/brands/facebook
          link: "https://facebook.com/autolabproject"
    analytics:
        provider: google
        property: G-PH5EYTKBNQ
markdown_extensions:
    - admonition
    - codehilite
      #linenums: true
strict: true
plugins:
  - search
