# SQLite Configuration used for Autolab Docker Deployments
development: &common
  adapter: sqlite3
  database: db/db.sqlite3
  pool: 5
  timeout: 5000

# SQLite Configuration
production:
  <<: *common
